### Required var:
#   - localhost_user

# Run as local user you want to provision

### Setup SSH Keys
- name: Local Key Setup
  hosts: localhost
  connection: local
  tasks:
  - name: Ensure ssh directory exist
    file:
      path: "{{ ansible_user_dir }}/.ssh"
      state: directory
      mode: '0700'
  - name: Ensure user account has ssh key pair generated
    openssh_keypair:
      path: "{{ ansible_user_dir }}/.ssh/id_rsa"