- name: Provision Fedora Desktop
  hosts: desktop
  vars_files:
    - vars/packages-common.yaml
    - vars/packages-fedora.yaml
  tasks:
  - name: (Fedora) Ensure Other Extra Fedora Repos are Enabled
    dnf:
      state: present
      name:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: yes
  - name: (Fedora) Ensure Packages are Present
    dnf:
      update_cache: yes
      name: "{{ common_packages + fedora_packages + fedora_kde_packages }}"
      allowerasing: yes
      state: present

- import_playbook: provision-snaps.yaml  
