- name: Provision Fedora Desktop
  hosts: desktop
  vars_files:
    - vars/packages-common.yaml
    - vars/packages-fedora.yaml
  tasks:
  - name: (Fedora) Upgrade all packages to the latest version
    dnf:
      name: "*"
      state: latest
    tags:
      - pkg_update
  - name: (Fedora) Ensure Other Extra Fedora Repos are Enabled
    dnf:
      state: present
      name:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: yes
  - name: (Fedora) Ensure Packages are Present
    dnf:
      update_cache: yes
      name: "{{ common_packages + fedora_packages + fedora_kde_packages}}"
      state: present
  - name: (Fedora) Ensure classic Snaps directory is linked
    file:
      src: /var/lib/snapd/snap
      dest: /snap
      owner: root
      group: root
      state: link
  - name: (Fedora) Finding Local rpms
    find:
      paths: "/home/{{ for_user }}/automated-install/rpm"
      patterns: "*.rpm"
    register: local_rpm_results
  - name: (Fedora) Prepare Local rpm List
    set_fact:
      rpm_paths: "{{ local_rpm_results.files | map(attribute='path') | list}}"
  - name: (Fedora) Ensure Local rpm Packages are Installed
    dnf:
      name: "{{ rpm_paths }}"
      state: present
      disable_gpg_check: yes
- import_playbook: provision-work-desktop-roles.yaml

  
