- name: Provision PopOS Desktop
  hosts: desktop
  vars_files:
    - vars/packages-common.yaml
    - vars/packages-pop.yaml
    - vars/packages-snaps.yaml
  tasks:
  - name: (Pop OS) Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      force_apt_get: yes
    tags:
      - pkg_update
  - name: (Pop OS) Ensure Packages are Present
    apt:
      update_cache: yes
      name: "{{ common_packages + pop_packages}}"
      state: present
  - name: (Pop OS) Ensure the msr module is present (for CPU monitoring)
    modprobe:
      name: msr
      state: present

  
