- name: Provision PopOS Desktop
  hosts: desktop
  vars_files:
    - vars/packages-common.yaml
    - vars/packages-pop.yaml
    - vars/packages-snaps.yaml
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      force_apt_get: yes
    tags:
      - pkg_update
  - name: Install Common packages
    apt:
      update_cache: yes
      name: "{{ common_packages }}"
      state: present
  - name: Install PopOS Specific packages
    apt:
      update_cache: yes
      name: "{{ pop_packages }}"
      state: present
  # TODO when Ubunutu gets with the times use podman instead of docker
  - name: Ensure docker group exists
    group:
      name: docker
      state: present
  - name: Ensure the target Users is in the Docker group
    user:
      name: "{{ for_user }}"
      groups: docker
      append: yes
  - name: Ensure the msr module is present (for CPU monitoring)
    modprobe:
      name: msr
      state: present
  - include: tasks/provision-common-desktop-tasks.yaml
- import_playbook: provision-common-desktop-roles.yaml
  
