- name: Provision Common Roles
  hosts: desktop
  vars_files:
    - vars/vs-code-extensions.yaml
    - vars/packages-pip.yaml
  roles:
    - role: chrome-role
    - role: brave-browser-role
    - role: gantsign.golang
      golang_gopath: '$HOME/dev/go-workspace'

    # GITHUB is here: https://github.com/gantsign/ansible-role-visual-studio-code
    - role: gantsign.visual-studio-code
#      users:
#        - username: "{{ for_user }}"
#          visual_studio_code_extensions: "{{ vs_code_extensions }}"

    - role: oc-role
    - role: argocd-cli-role
    - role: ms-teams-role
    - role: odo-role
    - role: geerlingguy.pip
    - role: gphoto-dslr-role
    - role: tekton-cli-role
    - role: helm-cli-role
    - role: knative-cli-role
    
