- name: Provision OpenMandriva Desktop
  hosts: desktop
  vars_files:
    - vars/packages-common.yaml
    - vars/packages-open-mandriva.yaml
  tasks:
  - name: (OpenMandriva) Ensure Packages are Present
    dnf:
      update_cache: yes
      name: "{{ common_packages + open_mandriva_packages + open_mandriva_kde_packages }}"
      allowerasing: yes
      state: present

  
