- name: Provision Common Roles
  hosts: desktop
  vars_files:
    - vars/vs-code-extensions.yaml
  roles:
    - role: gantsign.golang
      golang_gopath: '$HOME/dev/go-workspace'

    # GITHUB is here: https://github.com/gantsign/ansible-role-visual-studio-code
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ for_user }}"
          visual_studio_code_extensions: "{{ vs_code_extensions }}"

    - role: oc-role
      oc_archive: "{{ oc_archive }}"
      
    - role: argocd-cli-role
