- name: Provision Playbook
  hosts: desktop
  gather_facts: true

- name: Provision PopOS Desktops
  import_playbook: provision-pop_os-desktop.yaml
  when: ansible_distribution == 'Pop!_OS'

- name: Provision Fedora Desktops
  import_playbook: provision-fedora-desktop.yaml
  when: ansible_distribution == 'Fedora'

- name: Common Playbook Tasks
  hosts: desktop
  vars_files:
  - vars/packages-snaps.yaml
  tasks:
  - name: "Ensure user: {{ for_user }} is in the libvirt group"
    user:
      name: "{{ for_user }}"
      groups: libvirt
      append: yes

  - name: Ensure snapd is up
    ansible.builtin.service:
      name: snapd
      state: started

  - name: Ensure Snaps are installed
    snap:
      name: "{{ snap_packages }}"
    tags:
      - snap_pkgs

- import_playbook: provision-common-desktop-roles.yaml