- name: Provision apt Desktop
  hosts: desktop
  connection: local
  vars_files:
    - packages-common.yaml
    - packages-ubuntu.yaml
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      force_apt_get: yes
  - name: Add Google Apt Signing Key
    apt_key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      state: present
# FIXME This is doubling up entry 2nd runs and beyond which is sending a default utility CPU crazy
#  - name: Add Google-Chrome Repo
#    apt_repository:
#      repo: deb http://dl.google.com/linux/chrome/deb/ stable main
#      state: present
#      filename: google-chrome
  - name: Install Common packages
    apt:
      update_cache: yes
      name: "{{ common_packages }}"
      state: latest
  - name: Install Ubuntu packages
    apt:
      update_cache: yes
      name: "{{ ubuntu_packages }}"
      state: latest
  # TODO when Ubunutu gets with the times use podman instead of docker
  - name: Ensure docker group exists
    group:
      name: docker
      state: present
  - name: Ensure the target Users is in the Docker group
    user:
      name: "{{ for_user }}"
      groups: docker
      append: yes
  - include: provision-common-desktop-tasks.yaml
  # TODO this role needs work - mainly accepting EULA
  #roles:
  #  - make-mkv
  
