- name: Provision Playbook
  hosts: desktop
  gather_facts: true

- name: Provision PopOS Desktops
  import_playbook: provision-pop_os-desktop.yaml
  when: ansible_distribution == 'Pop!_OS'

- name: Provision Fedora Desktops
  import_playbook: provision-fedora-desktop.yaml
  when: ansible_distribution in ('Fedora', 'Nobara')

- name: Provision OpenMandriva Desktops
  import_playbook: provision-open-mandriva-desktop.yaml
  when: ansible_distribution == 'OpenMandriva'

- name: Common Playbook Tasks
  hosts: desktop
  tasks:
  - name: "Ensure user: {{ for_user }} is in the libvirt group"
    user:
      name: "{{ for_user }}"
      groups: libvirt
      append: yes

  - name: Ensure libvirtd is enable and started
    systemd:
      name: libvirtd
      enabled: yes
      state: started

- import_playbook: provision-common-desktop-roles.yaml
