- name: Ensure the target Users Groups are correct
  user:
    name: "{{ for_user }}"
    groups: libvirt
    append: yes
- name: Ensure Snaps are installed
  snap:
    name: "{{ snap_packages }}"
- name: Ensure classic Snaps are installed
  snap:
    name: "{{ snap_classic_packages }}"
    classic: yes
